title = "K2 System KnowledgeBase"
wellcome = "Wellcome to K2!"
datainput = "Data Input"
wellcome2 = "What are we going to do today?"
workspace= "Workspace"
alert = "Alerts"
register = "Please register to access K2!"
already = "Already have an account? Login!"
forgot= "Forgot Password?"
